export const STANDARDIZED_SKILLS = [
  // Programming Languages
  'JavaScript',
  'TypeScript',
  'Python',
  'Java',
  'C#',
  'C++',
  'C',
  'PHP',
  'Ruby',
  'Go',
  'Rust',
  'Swift',
  'Kotlin',
  'Dart',
  'Scala',
  'R',
  'MATLAB',
  'SQL',
  'HTML',
  'CSS',
  'SASS',
  'SCSS',

  // Frontend Frameworks & Libraries
  'React',
  'Vue.js',
  'Angular',
  'Svelte',
  'Next.js',
  'Nuxt.js',
  'Gatsby',
  'Redux',
  'MobX',
  'Zustand',
  'React Query',
  'SWR',
  'jQuery',
  'Bootstrap',
  'Tailwind CSS',
  'Material-UI',
  'Ant Design',
  'Chakra UI',

  // Backend Frameworks
  'Node.js',
  'Express.js',
  'Nest.js',
  'Django',
  'Flask',
  'FastAPI',
  'Spring Boot',
  'Spring Framework',
  'ASP.NET',
  'Rails',
  'Laravel',
  'Symfony',
  'Gin',
  'Echo',
  'Fiber',

  // Databases
  'PostgreSQL',
  'MySQL',
  'MongoDB',
  'Redis',
  'SQLite',
  'Oracle',
  'Microsoft SQL Server',
  'DynamoDB',
  'Cassandra',
  'Neo4j',
  'Firebase Firestore',
  'Supabase',

  // Cloud Platforms
  'AWS',
  'Google Cloud Platform',
  'Microsoft Azure',
  'DigitalOcean',
  'Heroku',
  'Vercel',
  'Netlify',
  'Railway',
  'PlanetScale',
  'Cloudflare',

  // AWS Services
  'EC2',
  'S3',
  'Lambda',
  'API Gateway',
  'RDS',
  'DynamoDB',
  'CloudFront',
  'Route 53',
  'CloudFormation',
  'ECS',
  'EKS',

  // DevOps & Tools
  'Docker',
  'Kubernetes',
  'Jenkins',
  'GitHub Actions',
  'GitLab CI',
  'CircleCI',
  'Terraform',
  'Ansible',
  'Chef',
  'Puppet',
  'Vagrant',
  'Nginx',
  'Apache',

  // Version Control
  'Git',
  'GitHub',
  'GitLab',
  'Bitbucket',
  'SVN',

  // Testing
  'Jest',
  'Cypress',
  'Selenium',
  'Playwright',
  'Mocha',
  'Chai',
  'PyTest',
  'JUnit',
  'TestNG',
  'Postman',
  'Insomnia',

  // Mobile Development
  'React Native',
  'Flutter',
  'iOS Development',
  'Android Development',
  'Xamarin',
  'Ionic',
  'Cordova',

  // Data Science & AI
  'TensorFlow',
  'PyTorch',
  'Scikit-learn',
  'Pandas',
  'NumPy',
  'Matplotlib',
  'Seaborn',
  'Jupyter',
  'Tableau',
  'Power BI',
  'Apache Spark',
  'Hadoop',

  // Design & UI/UX
  'Figma',
  'Adobe XD',
  'Sketch',
  'Adobe Photoshop',
  'Adobe Illustrator',
  'InVision',
  'Framer',
  'Canva',
  'UI/UX Design',
  'User Research',
  'Prototyping',
  'Wireframing',

  // Project Management
  'Agile',
  'Scrum',
  'Kanban',
  'JIRA',
  'Trello',
  'Asana',
  'Monday.com',
  'Notion',
  'Confluence',
  'Slack',
  'Microsoft Teams',

  // Business & Strategy
  'Business Strategy',
  'Strategic Planning',
  'Business Development',
  'Market Research',
  'Competitive Analysis',
  'SWOT Analysis',
  'Business Model Canvas',
  'Value Proposition Design',
  'Customer Discovery',
  'Product-Market Fit',
  'Go-to-Market Strategy',
  'Business Process Optimization',
  'Change Management',
  'Organizational Development',
  'Corporate Strategy',
  'Mergers & Acquisitions',
  'Due Diligence',
  'Financial Modeling',
  'Business Intelligence',
  'Data Analytics',
  'KPI Development',
  'Performance Metrics',
  'ROI Analysis',
  'Cost-Benefit Analysis',

  // Marketing & Digital Marketing
  'Digital Marketing',
  'Content Marketing',
  'Social Media Marketing',
  'Email Marketing',
  'Search Engine Optimization (SEO)',
  'Search Engine Marketing (SEM)',
  'Google Ads',
  'Facebook Ads',
  'Instagram Ads',
  'LinkedIn Ads',
  'TikTok Ads',
  'Programmatic Advertising',
  'Display Advertising',
  'Retargeting',
  'Marketing Automation',
  'Lead Generation',
  'Conversion Rate Optimization',
  'A/B Testing',
  'Marketing Analytics',
  'Google Analytics',
  'Facebook Pixel',
  'Marketing Attribution',
  'Customer Journey Mapping',
  'Brand Strategy',
  'Brand Identity',
  'Brand Positioning',
  'Marketing Strategy',
  'Campaign Management',
  'Influencer Marketing',
  'Affiliate Marketing',
  'Public Relations',
  'Media Relations',
  'Crisis Communications',

  // Sales & Business Development
  'Sales Strategy',
  'Sales Process',
  'Lead Qualification',
  'Sales Pipeline Management',
  'CRM Systems',
  'Salesforce',
  'HubSpot',
  'Pipedrive',
  'Sales Training',
  'Negotiation',
  'Contract Management',
  'Account Management',
  'Customer Success',
  'Business Development',
  'Partnership Development',
  'Channel Sales',
  'B2B Sales',
  'B2C Sales',
  'Enterprise Sales',
  'Solution Selling',
  'Consultative Selling',

  // Finance & Accounting
  'Financial Planning',
  'Budgeting',
  'Forecasting',
  'Financial Analysis',
  'Financial Modeling',
  'Variance Analysis',
  'Cash Flow Management',
  'Working Capital Management',
  'Investment Analysis',
  'Portfolio Management',
  'Risk Management',
  'Internal Controls',
  'Audit Preparation',
  'Tax Planning',
  'Cost Accounting',
  'Managerial Accounting',
  'QuickBooks',
  'Xero',
  'Sage',
  'Excel Financial Modeling',

  // Operations & Supply Chain
  'Operations Management',
  'Process Improvement',
  'Lean Six Sigma',
  'Supply Chain Management',
  'Inventory Management',
  'Logistics',
  'Procurement',
  'Vendor Management',
  'Quality Management',
  'ISO Standards',
  'Continuous Improvement',
  'Workflow Optimization',
  'Capacity Planning',
  'Resource Allocation',

  // Human Resources
  'HR Strategy',
  'Talent Acquisition',
  'Recruitment',
  'Employee Onboarding',
  'Performance Management',
  'Employee Engagement',
  'Training & Development',
  'Compensation & Benefits',
  'HR Analytics',
  'Workplace Culture',
  'Diversity & Inclusion',
  'Employee Relations',
  'HR Compliance',
  'Workday',
  'BambooHR',
  'Greenhouse',

  // Legal & Compliance
  'Contract Law',
  'Employment Law',
  'Intellectual Property',
  'Data Privacy',
  'GDPR Compliance',
  'CCPA Compliance',
  'Regulatory Compliance',
  'Corporate Governance',
  'Risk Assessment',
  'Compliance Auditing',

  // Creative & Design
  'Graphic Design',
  'Logo Design',
  'Brand Identity Design',
  'Print Design',
  'Digital Design',
  'Web Design',
  'Mobile App Design',
  'Icon Design',
  'Typography',
  'Color Theory',
  'Layout Design',
  'Illustration',
  'Digital Art',
  '3D Modeling',
  'Animation',
  'Motion Graphics',
  'Video Editing',
  'Photo Editing',
  'Product Photography',
  'Food Photography',
  'Portrait Photography',
  'Event Photography',

  // Content Creation
  'Content Strategy',
  'Content Creation',
  'Copywriting',
  'Technical Writing',
  'Creative Writing',
  'Blog Writing',
  'Social Media Content',
  'Email Copywriting',
  'Landing Page Copy',
  'Product Descriptions',
  'Case Studies',
  'White Papers',
  'E-books',
  'Video Scripts',
  'Podcast Scripts',
  'Content Calendar',
  'Editorial Calendar',

  // Video & Audio
  'Video Production',
  'Video Editing',
  'Motion Graphics',
  'Animation',
  'Sound Design',
  'Audio Editing',
  'Podcast Production',
  'Live Streaming',
  'YouTube Strategy',
  'TikTok Content',
  'Instagram Reels',
  'Adobe Premiere Pro',
  'Final Cut Pro',
  'DaVinci Resolve',
  'After Effects',
  'Audition',

  // E-commerce & Retail
  'E-commerce Strategy',
  'Shopify',
  'WooCommerce',
  'Amazon FBA',
  'Etsy',
  'Online Store Management',
  'Product Photography',
  'Inventory Management',
  'Order Fulfillment',
  'Customer Service',
  'Returns Management',
  'Payment Processing',
  'Shipping & Logistics',

  // Consulting & Advisory
  'Management Consulting',
  'Strategy Consulting',
  'IT Consulting',
  'Digital Transformation',
  'Change Management',
  'Process Consulting',
  'Financial Consulting',
  'HR Consulting',
  'Marketing Consulting',
  'Sales Consulting',
  'Operations Consulting',
  'Technology Consulting',
  'Business Process Outsourcing',
  'Interim Management',

  // Freelance & Entrepreneurship
  'Freelance Business',
  'Client Management',
  'Project Management',
  'Time Management',
  'Invoicing',
  'Contract Negotiation',
  'Business Development',
  'Networking',
  'Personal Branding',
  'Portfolio Development',
  'Pricing Strategy',
  'Service Delivery',
  'Customer Relationship Management',
  'Business Operations',
  'Financial Management',
  'Tax Planning',
  'Insurance',
  'Legal Compliance',

  // Industry-Specific Skills
  'Healthcare Consulting',
  'Financial Services',
  'Technology Sector',
  'Manufacturing',
  'Retail',
  'Real Estate',
  'Education',
  'Non-profit',
  'Government',
  'Startup Ecosystem',
  'SaaS',
  'Fintech',
  'Healthtech',
  'Edtech',
  'E-commerce',
  'Digital Media',
  'Entertainment',
  'Sports',
  'Fashion',
  'Food & Beverage',
  'Automotive',
  'Aerospace',
  'Energy',
  'Sustainability',

  // Other Technologies
  'GraphQL',
  'REST API',
  'WebSockets',
  'gRPC',
  'Microservices',
  'Serverless',
  'JAMstack',
  'Progressive Web Apps',
  'Single Page Applications',
  'Responsive Design',
  'Cross-browser Compatibility',
  'Web Accessibility',
  'SEO',
  'Web Performance',
  'API Design',
  'Database Design',
  'System Architecture',
  'Technical Writing',
  'Code Review',
  'Mentoring',
  'Team Leadership',
]

export function searchSkills(query: string): string[] {
  if (!query.trim()) return STANDARDIZED_SKILLS

  const lowerQuery = query.toLowerCase()
  return STANDARDIZED_SKILLS.filter(skill => 
    skill.toLowerCase().includes(lowerQuery)
  ).sort()
}

export function getSkillSuggestions(query: string, limit: number = 10): string[] {
  return searchSkills(query).slice(0, limit)
}