export const STANDARDIZED_SKILLS = [
  // Programming Languages
  'JavaScript',
  'TypeScript',
  'Python',
  'Java',
  'C#',
  'C++',
  'C',
  'PHP',
  'Ruby',
  'Go',
  'Rust',
  'Swift',
  'Kotlin',
  'Dart',
  'Scala',
  'R',
  'MATLAB',
  'SQL',
  'HTML',
  'CSS',
  'SASS',
  'SCSS',

  // Frontend Frameworks & Libraries
  'React',
  'Vue.js',
  'Angular',
  'Svelte',
  'Next.js',
  'Nuxt.js',
  'Gatsby',
  'Redux',
  'MobX',
  'Zustand',
  'React Query',
  'SWR',
  'jQuery',
  'Bootstrap',
  'Tailwind CSS',
  'Material-UI',
  'Ant Design',
  'Chakra UI',

  // Backend Frameworks
  'Node.js',
  'Express.js',
  'Nest.js',
  'Django',
  'Flask',
  'FastAPI',
  'Spring Boot',
  'Spring Framework',
  'ASP.NET',
  'Rails',
  'Laravel',
  'Symfony',
  'Gin',
  'Echo',
  'Fiber',

  // Databases
  'PostgreSQL',
  'MySQL',
  'MongoDB',
  'Redis',
  'SQLite',
  'Oracle',
  'Microsoft SQL Server',
  'DynamoDB',
  'Cassandra',
  'Neo4j',
  'Firebase Firestore',
  'Supabase',

  // Cloud Platforms
  'AWS',
  'Google Cloud Platform',
  'Microsoft Azure',
  'DigitalOcean',
  'Heroku',
  'Vercel',
  'Netlify',
  'Railway',
  'PlanetScale',
  'Cloudflare',

  // AWS Services
  'EC2',
  'S3',
  'Lambda',
  'API Gateway',
  'RDS',
  'DynamoDB',
  'CloudFront',
  'Route 53',
  'CloudFormation',
  'ECS',
  'EKS',

  // DevOps & Tools
  'Docker',
  'Kubernetes',
  'Jenkins',
  'GitHub Actions',
  'GitLab CI',
  'CircleCI',
  'Terraform',
  'Ansible',
  'Chef',
  'Puppet',
  'Vagrant',
  'Nginx',
  'Apache',

  // Version Control
  'Git',
  'GitHub',
  'GitLab',
  'Bitbucket',
  'SVN',

  // Testing
  'Jest',
  'Cypress',
  'Selenium',
  'Playwright',
  'Mocha',
  'Chai',
  'PyTest',
  'JUnit',
  'TestNG',
  'Postman',
  'Insomnia',

  // Mobile Development
  'React Native',
  'Flutter',
  'iOS Development',
  'Android Development',
  'Xamarin',
  'Ionic',
  'Cordova',

  // Data Science & AI
  'TensorFlow',
  'PyTorch',
  'Scikit-learn',
  'Pandas',
  'NumPy',
  'Matplotlib',
  'Seaborn',
  'Jupyter',
  'Tableau',
  'Power BI',
  'Apache Spark',
  'Hadoop',

  // Design & UI/UX
  'Figma',
  'Adobe XD',
  'Sketch',
  'Adobe Photoshop',
  'Adobe Illustrator',
  'InVision',
  'Framer',
  'Canva',
  'UI/UX Design',
  'User Research',
  'Prototyping',
  'Wireframing',

  // Project Management
  'Agile',
  'Scrum',
  'Kanban',
  'JIRA',
  'Trello',
  'Asana',
  'Monday.com',
  'Notion',
  'Confluence',
  'Slack',
  'Microsoft Teams',

  // Other Technologies
  'GraphQL',
  'REST API',
  'WebSockets',
  'gRPC',
  'Microservices',
  'Serverless',
  'JAMstack',
  'Progressive Web Apps',
  'Single Page Applications',
  'Responsive Design',
  'Cross-browser Compatibility',
  'Web Accessibility',
  'SEO',
  'Web Performance',
  'API Design',
  'Database Design',
  'System Architecture',
  'Technical Writing',
  'Code Review',
  'Mentoring',
  'Team Leadership',
]

export function searchSkills(query: string): string[] {
  if (!query.trim()) return STANDARDIZED_SKILLS

  const lowerQuery = query.toLowerCase()
  return STANDARDIZED_SKILLS.filter(skill => 
    skill.toLowerCase().includes(lowerQuery)
  ).sort()
}

export function getSkillSuggestions(query: string, limit: number = 10): string[] {
  return searchSkills(query).slice(0, limit)
}